### ISSUE TITLE
the convector is not displaying...

### ISSUE THREAD

**Issue by unnamedusers** [SheepTester/htmlifier#108]
some thing is wrong, its only displaying the version history and the below only, the error that i found :
Uncaught SyntaxError: Unexpected token ? at https://sheeptester.github.io/htmlifier/index.bundle.min.js:1:23619

https://user-images.githubusercontent.com/88642958/128658865-e6e1457b-9f2a-48b7-8b04-504514d01c77.mp4

**Comment by SheepTester** [comment]
What version of Chrome are you using? The `??` nullish coalescing operator should be supported in [Chrome 80+](https://caniuse.com/mdn-javascript_operators_nullish_coalescing)

**Comment by unnamedusers** [comment]
ver. 73, well, i gnna use older version, maybe because i cant update my chrome
