### ISSUE TITLE
Can Sprites Uploaded enjoy all HTMLifier Features?

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#113]
### Can Sprites Uploaded enjoy all HTMLifier Features?

Like.... Can the variables in sprites uploaded in an HTMLified Project exhibit special behaviours for certain cloud variables if that checkbox is ticked while packaging the project?

**Comment by SparkScratch-P** [comment]
If not, can this feature be added?

**Comment by SheepTester** [comment]
It behaves the same as uploading the sprite in the editor, so if uploading a sprite using special cloud variables works in the editor, then it works when HTMLified.

**Comment by SparkScratch-P** [comment]
Ok Thanks!
[image: GeoTrack]
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
Sender
notified with GeoTrack
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
[image: 5]
