### ISSUE TITLE
New Feature Request : Upload Multiple Extensions while a project is Running!

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#114]
One more feature request ! 

 Can u add one more button there, so that we can upload not only sprites but also add extensions in an HTMLified project?

WIll Wait!

Bye.

**Comment by SheepTester** [comment]
Adding extensions wouldn't do anything since it wouldn't modify the blocks used

**Comment by SparkScratch-P** [comment]
Ok Thanks.
[image: GeoTrack]
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
Sender
notified with GeoTrack
<https://geotrack.email/?utm_source=gmail&utm_medium=signature&utm_campaign=viralSignature>
[image: 2]
