### ISSUE TITLE
Cloud server issues

### ISSUE THREAD

**Issue by Addienz** [SheepTester/htmlifier#117]
I facing a lot of difficulty actually getting projects to start when using a custom cloud server.
They seemed to have done this when they couldn't connect, but only when you're actually changing a cloud variable would it hang.
Now the projects hang immediately on load after the HTMLifier update when using a custom server.
I had the server working perfectly before. 
I reinstalled node, and the server, and yet any projects made after the update seem to not load. I've checked IP's, made sure to include ws:// at the start of the address and included the port with a colon and /.
I'm essentially asking if I'm doing something wrong, or, if I'm not, that somehow the cloud variables broke.

If I'm doing anything obviously incorrect then you can blame me, I'm pretty stupid.

**Comment by SheepTester** [comment]
Not your fault; I broke connecting to cloud servers when I rewrote the HTMLifier. Fixed in bfdf4275c7b967063ccb286f314def4abd8890db
