### ISSUE TITLE
Allow project to extract data from other websites.

### ISSUE THREAD

**Issue by vicwolrocket** [SheepTester/htmlifier#119]
Hi! I used your HTMLifier many times and I love it! There is only one suggestion I want to make. Wouldn't it be cool if the htmlified project could extract data from other websites? Like if I set a cloud variable called "extract data" to "https://pastebin.com/raw/e7ShQPKn", it would set that cloud variable to "This is a test!".

**Comment by SheepTester** [comment]
Browsers enforce a [CORS policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) preventing web pages from fetching content from other websites across different domains. These domains can opt out of this restriction, but it appears that Pastebin does not have CORS enabled.

![image](https://user-images.githubusercontent.com/22133785/129453573-80d2a0b4-5e47-4c04-a698-f4b9f5216e64.png)

Regardless, you can use my [Utilities extension](https://sheeptester.github.io/javascripts/utilities.js), which has a `get content from _` block. [E羊icques](https://sheeptester.github.io/scratch-gui/) and [Turbowarp](http://turbowarp.org/) let you use unofficial extensions from a URL (e.g. https://sheeptester.github.io/javascripts/utilities.js). 

![image](https://user-images.githubusercontent.com/22133785/129453643-274b19b5-7f31-49ed-a70d-402cac1aa944.png)

Then in the HTMLifier, you can add the extension URL under "Load unofficial extension from URL:"

![image](https://user-images.githubusercontent.com/22133785/129454466-ad4e9445-d318-4824-9d7b-36913f94ac04.png)

**Comment by vicwolrocket** [comment]
Thanks!
