### ISSUE TITLE
Aspect ratio issue

### ISSUE THREAD

**Issue by vicwolrocket** [SheepTester/htmlifier#126]
If you try to use a custom aspect ratio, the backdrop and lists are positioned in the wrong way. When I tried it with a project the lists x position was changed and the backdrops position completely changed.

**Comment by SheepTester** [comment]
I believe list and variable watchers are based on the top left corner rather than the middle of the stage. You can try opening the project in [E羊icques](https://sheeptester.github.io/scratch-gui/flags.html) with your desired stage size to adjust the list/variable watchers before HTMLifying

**Comment by vicwolrocket** [comment]
OK, now I understand.
