### ISSUE TITLE
html to exe request

### ISSUE THREAD

**Issue by micromakerstudio** [SheepTester/htmlifier#134]
Can you make a HTML-TO-EXE website or application?
Thank you!And your projects are very nice!

**Comment by SheepTester** [comment]
The [TurboWarp Packager](https://packager.turbowarp.org/) is capable of producing exe files. You can also follow this tutorial: https://scratch.mit.edu/discuss/topic/341617/

Because alternatives already exist, I will probably not invest time in creating another one
