### ISSUE TITLE
Need A Studio or Library for HTMLified Projects?

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#140]
### Hi! SheepMaker!

**Its [SparkScratch-P](https://sparkscratch-p.github.io/)**

 I saw TurboWarp has a  Studio, that has projects that work best on TurboWarp!
  
  TurboWarp makes projects faster only! But HTMLifier modifies a lot, and has features that make many impossible things possible!
  So, Would You Accept if I create an HTMLifier Studio, by forking this repo? It will have projects, whose majority of features are possible only with HTML.
   Some basic Examples from my Experience that makes HTMLifier the most Special one:

1.  [ EvalJS](https://sparkscratch-p.github.io/EvalJS/)
2.  [SyncPixee](https://sparkscratch-p.github.io/Syncpixee/)
3.  [ArchieBulid](https://sparkscratch-p.github.io/ArchieBuild/)

And I am sure...there are far more over the Web!
I will create everything; collapse, a bit of CSS (though if u want to maintain these as one of the mail HTMLifier, u need to add the basic CSS), contribution guidelines, and some more!

## Thank You
Pls visit my page, https://sparkscratch-p.github.io/ React, Rate and Comment!

**Comment by SheepTester** [comment]
> TurboWarp makes projects faster only!

This is far from true; TurboWarp's feature set encompasses the HTMLifier's (except for unprotected eval, for reasonable reasons) and more

> So, Would You Accept if I create an HTMLifier Studio, by forking this repo? It will have projects, whose majority of features are possible only with HTML.

GitHub's TOS permits you to fork any repository without having to ask. "The HTMLifier" isn't trademarked or anything so you're free to use it in the name of whatever you make

**Comment by SparkScratch-P** [comment]
> This is far from true; TurboWarp's feature set encompasses the HTMLifier's (except for unprotected eval, for reasonable reasons) and more

 Hmmm maybe.. from the very beginning I went on for exporting and publishing scratch projects, the first thing i got is HTMLifier, Hence, I don't know much bout TurboWarp. And about the studio, TurboWarps studio has projects tht are made only faster, I mean works faster with it than Scratch!
 
 

> GitHub's TOS permits you to fork any repository without having to ask. "The HTMLifier" isn't trademarked or anything so you're free to use it in the name of whatever you make

Ofc! but the thing is that I won't do anything that no one needs! Like, if u want a studio, I will do, but not waste over something unacceptable. So, if u like my idea, pls tell me, brother.. I will do it.

**Comment by SheepTester** [comment]
> Ofc! but the thing is that I won't do anything that no one needs! Like, if u want a studio, I will do,

Ah, I don't think a studio for projects that work better with the HTMLifier is needed right now

**Comment by SparkScratch-P** [comment]
Om Bro, and if ever u need any, pls notify me... I will surely like to help😊 👨‍💻
