### ISSUE TITLE
Question about Eval and Blockly variables

### ISSUE THREAD

**Issue by cataghg** [SheepTester/htmlifier#143]
-Can you define a blockly variable using it? (after project is loaded)

-Can you modify already existent variables? (player position for example)

-Can you brodcast a message using it?

 -If it is not possible with blockly, than is it possible with something else?

- And if it is, than could you show me a example that I could test?

  Thank you once again for your time.

**Comment by SheepTester** [comment]
You can create/change variables and broadcast messages but not using Blockly. Rather, you'd use [scratch-vm](https://github.com/LLK/scratch-vm/), an instance of which is made global via `Scratch.vm`

```js
const stage = Scratch.vm.runtime.getTargetForStage()
const wowVar = stage.lookupOrCreateVariable('wow')
console.log(wowVar.value) // 0 by default
wowVar.value = 3
```

**Comment by cataghg** [comment]
Thanks a lot for the help!

**Comment by cataghg** [comment]
I have another question on how you found the text representation to "run" scratch blocks. Because I searched a lot and didn't find anything.

**Comment by SheepTester** [comment]
Scratch blocks are represented as text in the form of JSON. If you download a project, rename it to a .zip, then extract it, the project.json file will contain the blocks' text representation

**Comment by cataghg** [comment]
I tried running ```
Scratch.vm.runtime.startHats('event_whenbroadcastreceived', {
  BROADCAST_OPTION: 'message1'
})
```
and it didn't work... It says Scratch is not defined. Shouldn't it be defined and all that?

**Comment by SheepTester** [comment]
Scratch should be defined in HTMLified projects

**Comment by cataghg** [comment]
> `Scratch` should be defined in HTMLified projects

I just did and `vm.runtime.startHats('event_whenbroadcastreceived', { BROADCAST_OPTION: 'e' }) `worked

**Comment by cataghg** [comment]
Is there any documentation for more stuff? Like moving a sprite or modifying any of it's properties?

**Comment by SheepTester** [comment]
https://llk.github.io/scratch-vm/docs/

**Comment by cataghg** [comment]
> https://llk.github.io/scratch-vm/docs/

Thanks, but I still don't understand how to modify sprite properties. For example rotation or position. Wold you mind giving me some examples. Sorry for asking for so much help btw.

**Comment by SheepTester** [comment]
You can look at how the motion blocks are defined

https://github.com/LLK/scratch-vm/blob/d86546d2a2a34d3e367ff3a3b1ecccd99b5861a5/src/blocks/scratch3_motion.js#L116-L119

https://github.com/LLK/scratch-vm/blob/d86546d2a2a34d3e367ff3a3b1ecccd99b5861a5/src/blocks/scratch3_motion.js#L72-L76

**Comment by cataghg** [comment]
> You can look at how the motion blocks are defined
> 
> https://github.com/LLK/scratch-vm/blob/d86546d2a2a34d3e367ff3a3b1ecccd99b5861a5/src/blocks/scratch3_motion.js#L116-L119
> 
> https://github.com/LLK/scratch-vm/blob/d86546d2a2a34d3e367ff3a3b1ecccd99b5861a5/src/blocks/scratch3_motion.js#L72-L76

Example that I could use for any of those? So I understand the syntax, since that is my main issues rn, I do not understand how specify what sprite I wanna modify and all that.

**Comment by SheepTester** [comment]
You can use `vm.runtime.getSpriteTargetByName(spriteName)` to get a sprite by its name or `vm.runtime.getTargetForStage()` for the stage

**Comment by cataghg** [comment]
thank you! That is exactly what I wanted.

**Comment by cataghg** [comment]
> You can use `vm.runtime.getSpriteTargetByName(spriteName)` to get a sprite by its name or `vm.runtime.getTargetForStage()` for the stage

weird... that gives me an error, saying it isn't defined `
`

**Comment by cataghg** [comment]
nvm, forgot to put it in ('Sprite1')
