### ISSUE TITLE
> the HTML file in the zip file can't be directly opened in the browser

### ISSUE THREAD

**Issue by debian-user-france1** [SheepTester/htmlifier#147]
> the HTML file in the zip file can't be directly opened in the browser

I think I just found out why my old projects dont work anymore

_Originally posted by @Ganheso in https://github.com/SheepTester/htmlifier/issues/146#issuecomment-1031872668_

Please add a guide how they can run a Webserver with Python (a simple command) because it won't work else

**Comment by ShipmasterKyle** [comment]
Where are you hosting the py server?

Sean made a (Primitive Cloud Server)[https://github.com/SheepTester/primitive-cloud-server] that works well with all projects or you could just let the data save to localhost.

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/152878413-b6f3636d-d1c7-46b7-ba30-9daf9af81c85.png)

**Comment by debian-user-france1** [comment]
Ah and a simple solution is missing

Solution:
`Install Python 3
Run python3 -m http.server 8085
Open the browser with: localhost:8085 (no secure connection required)`

I would like that you add that. No external hosting required.

**Comment by debian-user-france1** [comment]
Would you do that? Every 'noob' (I don't like to say noob) would be able to do that. Maybe you should add the information that they have to open the power shell (without root permission) or a terminal.

**Comment by ShipmasterKyle** [comment]
> Ah and a simple solution is missing
> 
> Solution:
> 
> ```
> install Python 3
> Run python3 -m http.server 8085
> Open the browser with: localhost:8085 (no secure connection required)
> ```
> 
> I would like that you add that. No external hosting required.

This method runs on localhost so its only available to the user who is hosting the server. If thats the intention then that works.

**Comment by debian-user-france1** [comment]
Well I just asked if you could do that (@SheepTester ).

Of course it's meant for localhost (the hoster) only because everybody is able to do that if the one has the zip file. Anybody that wants to go further has to know how IPs (the whole network) work, how a connection is made and how to use Python.

**Comment by SheepTester** [comment]
> Ah and a simple solution is missing
> 
> Solution:
> 
> ```
> install Python 3
> Run python3 -m http.server 8085
> Open the browser with: localhost:8085 (no secure connection required)
> ```
> 
> I would like that you add that. No external hosting required.

https://github.com/SheepTester/htmlifier/wiki/Downloading-as-a-.zip#hosting-locally

**Comment by debian-user-france1** [comment]
No I didn't
