### ISSUE TITLE
Result file gets detected as Trojan by Microsoft Windows Defender

### ISSUE THREAD

**Issue by Wanja01YT** [SheepTester/htmlifier#156]
The resulting HTML file is detected as a Wacatac Trojan by Microsoft Defender, while not very believable due to many false positives by Microsoft Defender, this is still making the project suspicious in its safety

![image](https://github.com/SheepTester/htmlifier/assets/62118688/034ed51b-4dfa-4637-a5aa-966478acf214)

**Comment by SheepTester** [comment]
https://github.com/sixem/ivfi-php/issues/48#issuecomment-2049867952

appears to be a false positive that tends to happen with any file that has JavaScript in it. not much I can do on my end
