### ISSUE TITLE
Unknown error when converting

### ISSUE THREAD

**Issue by jonloveslegos** [SheepTester/htmlifier#23]
It gives a error when i try to convert.
I need this fixed or tell me what is wrong so i can update my game on GameJolt.
----------------------------------------------------------------------------------------------
Unexpected error:
TypeError: Cannot read property 'assetId' of null
    at g (https://sheeptester.github.io/scratch-vm/16-9/vm.min.js:14:186667)
    at https://sheeptester.github.io/scratch-vm/16-9/vm.min.js:14:187321
-----------------------------------------------------------------------------------------

**Comment by SheepTester** [comment]
What is the project that you're trying to convert?

**Comment by jonloveslegos** [comment]
https://scratch.mit.edu/projects/397489263/editor/
I found out the problem though, it fails to convert blank sprites.

**Comment by SheepTester** [comment]
Hmm, I was able to convert both that project and [this test project with a blank sprite](https://scratch.mit.edu/projects/411066875/) successfully. What OS/browser are you using?

**Comment by jonloveslegos** [comment]
Edit my project to have blank sprites for the ones that are hidden.
OS is windows 10 and browser is google chrome.

**Comment by SheepTester** [comment]
Ah, okay. So it works now?

**Comment by jonloveslegos** [comment]
It only started working after i replaced the blank sprites with random pixels.
