### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Richienb** [SheepTester/htmlifier#27]
It would be useful if htmlifier provided an API that acted as an alternative to the web UI. At the moment, I'm having to [launch a headless browser](https://github.com/Richienb/scratch-builder/blob/d0894fe83c90846ea308c7f80ae347fba0bba4b5/lib/build-html.js) to do this.

// @SheepTester

**Comment by Galaxy-Coding** [comment]
Nice Idea @Richienb 
// @SheepTester
