### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by buccimichele5** [SheepTester/htmlifier#35]
Hello! I tried multiple times to convert the project 236029109. I tried multiple times  but still cant make it work. Basically, a white screen appears, the loading says 1/1 but still nothing happens, even if I reload. Any advice?

**Comment by SheepTester** [comment]
Interesting, it works for me. Are there any errors in the console?

**Comment by buccimichele5** [comment]
Says the following:
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. <URL>
index.html:1 Access to XMLHttpRequest at 'file:///C:/Users/bucci/Downloads/Test/project.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
project.json:1 Failed to load resource: net::ERR_FAILED
index.html:912 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at index.html:912
index.html:292 Uncaught TypeError: Cannot read property 'draggable' of undefined
    at A.value (index.html:292)
    at B.value (index.html:288)
    at HTMLCanvasElement.mousedown (index.html:734)
index.html:292 Uncaught TypeError: Cannot read property 'draggable' of undefined
    at A.value (index.html:292)
    at B.value (index.html:288)
    at HTMLDocument.mouseup (index.html:759)`

And uh, I have no clue what this all means xD

**Comment by SheepTester** [comment]
Ah, it seems like you downloaded the HTMLified project as a .zip, but you opened the HTML file within directly in your browser (as a file:// URL). Browsers have security policies for local files that prevent HTMLified projects from working.

However, you can host the files online (like with Github Pages) or start a local HTTP server, and then it should load properly

**Comment by buccimichele5** [comment]
Ok alright. Will try this thanks

**Comment by buccimichele5** [comment]
seems to work, thanks
