### ISSUE TITLE
Trouble using HTMLified file on Github pages

### ISSUE THREAD

**Issue by Galaxy-Coding** [SheepTester/htmlifier#36]
My repository [https://github.com/Galaxy-Coding/dodge-the-demon](https://github.com/Galaxy-Coding/dodge-the-demon) will not work on Github Pages. The file is named index.html and I did everything to enable GH-Pages. There is a [Error 404](https://galaxy-coding.github.io/dodge-the-demon) at my Github Site and the url for the “successful” GH-pages build is here: [https://github.com/Galaxy-Coding/dodge-the-demon/runs/1091448975](https://github.com/Galaxy-Coding/dodge-the-demon/runs/1091448975). Thanks for your help in advance
@SheepTester

**Comment by SheepTester** [comment]
Works for me? https://galaxy-coding.github.io/dodge-the-demon/

Maybe the 404 error was cached on your end; you can add question marks at the end of the URL when that happens to try to combat it

**Comment by Galaxy-Coding** [comment]
// @SheepTester Thank you. Sadly, Github Pages takes several hours for me to update
