### ISSUE TITLE
Downloading as .zip doesn't work for .sb2 files

### ISSUE THREAD

**Issue by SheepTester** [SheepTester/htmlifier#50]
It's trying to fetch from hashes but the file doesn't have them
![image](https://user-images.githubusercontent.com/22133785/100536603-9e16f880-31d6-11eb-9d15-5ba3f2648c88.png)
![image](https://user-images.githubusercontent.com/22133785/100536608-a3744300-31d6-11eb-8774-4f0a816c3a68.png)

**Comment by DennieMello** [comment]
Yes, I met the same problem. I'm really looking forward to the fix.

**Comment by JaredYoshi** [comment]
convert it to sb3
