### ISSUE TITLE
Can't click back on project to select after using var with slider

### ISSUE THREAD

**Issue by card100** [SheepTester/htmlifier#54]
If you have an event that takes keyboard input, the project needs to be selected to receive the input. However, if you change the slider on a variable, you can't click back on the rest of the project to go back to select it. 

I probably did a terrible job explaining that so here's an example. HTMLify the project 467212485. Try holding space. Then try changing the value of the variable and holding space again.  

Scratch annoyingly acts similar (as you can see with the same project [here](https://scratch.mit.edu/projects/467212485/)). It would be nice if there was an option to not have the game deselected when you use a slider.

**Comment by SheepTester** [comment]
> It would be nice if there was an option to not have the game deselected when you use a slider.

I have just made this the default behaviour; hopefully no one relies on keyboard focus for the slider
