### ISSUE TITLE
Possible to support multi-touch?

### ISSUE THREAD

**Issue by mughesic** [SheepTester/htmlifier#62]
This (example) scratch project works on an iPad - I made it for young music students who are only using iPads for remote learning. 
https://scratch.mit.edu/projects/432878100/

If I share the original scratch project multi-touch works great but overall I prefer the way the packaged project runs AND prefer the ability to change the aspect ratio. Is it possible to add an event listener to support multitouch? I tried editing the HTML, but I'm in way over my head. Something like what's mentioned here: https://www.html5rocks.com/en/mobile/touch/

Many thanks for your time!

**Comment by SheepTester** [comment]
It's certainly possible to detect multitouch with JavaScript. However, Scratch itself doesn't know how to deal with multiple pointers at once since it assumes that there is only one mouse x and only one mouse y at a time. 

Also, at least for me, multi-touch seems to work the same on both the Scratch website and when HTMLified: holding down two fingers on different keys at the same time only plays one of the notes.

**Comment by mughesic** [comment]
Wow thanks for the quick response, Sean!

I realized I had been sending students the version run on forkphorus: https://forkphorus.github.io/app.html?id=432878100. Interestingly, the standalone "HTML packager" on that site doesn’t work for multi-touch either.


Is it something I could add to the html code based on how my music students are using it?


Cheers,
Scott


On January 16, 2021 at 11:22 PM, Sean <notifications@github.com> wrote:






It's certainly possible to detect multitouch with JavaScript. However, Scratch itself doesn't know how to deal with multiple pointers at once since it assumes that there is only one mouse x and only one mouse y at a time.

Also, at least for me, multi-touch seems to work the same on both the Scratch website and when HTMLified: holding down two fingers on different keys at the same time only plays one of the notes.

**Comment by SheepTester** [comment]
The "when sprite clicked block" only supports one finger at a time, unfortunately. However, it would be possible to add buttons to the HTML that simulate key presses since Scratch does support detecting multiple keys being held down.

**Comment by mughesic** [comment]
OK many thanks again. I was hoping “touch events” could be to “mouse down” but sounds like no such luck. Thanks for making HTMLify happen and for taking the time to check on this for me!


On January 17, 2021 at 11:20 PM, Sean <notifications@github.com> wrote:






The "when sprite clicked block" only supports one finger at a time, unfortunately. However, it would be possible to add buttons to the HTML that simulate key presses since Scratch does support detecting multiple keys being held down.
