### ISSUE TITLE
Scratch servers?

### ISSUE THREAD

**Issue by sargent-coding** [SheepTester/htmlifier#65]
Can you make it so a project can connect to Scratch's servers, instead of using a localhost?

**Comment by SheepTester** [comment]
No; that would require them to sign in, and making a third party sign-in form would be phishing, which is illegal. I'm pretty sure there's also a CORS policy preventing other sites from connecting to Scratch's cloud servers

**Comment by OldGuy111** [comment]
Yea; even SheepTester admitted that:
>**The [TurboWarp Packager](https://packager.turbowarp.org/) has better performance and can produce .exe files.**
