### ISSUE TITLE
I want to store data in an advanced cloud server.

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#68]
Can I host my data or cloud vars from cloud servers like one from fosshost.org ?
What data should I provide in a custom server box?
Can I provide an URL anyway?

Pls help me.

**Thank You**

**Comment by SheepTester** [comment]
If the cloud server is compatible with Scratch's cloud server protocol, then it'll work. You have to put a URL (cloud servers use WebSockets, so the URL should start with `ws://` or `wss://`) in the custom server URL box

**Comment by SparkScratch-P** [comment]
Thanks for ur help
