### ISSUE TITLE
My project is not working correctly after update

### ISSUE THREAD

**Issue by iPaCXgames** [SheepTester/htmlifier#7]
My project is not working correctly after update. Some scripts are not working... How can I download previous versions of HTMLifier ?

**Comment by SheepTester** [comment]
The last version of the HTMLifier was in a different repository, so clone https://github.com/SheepTester/words-go-here/, `git checkout` to the hash of the commit of some previous version, and serve the repository locally using something like [http-server](https://www.npmjs.com/package/http-server)

I could also try fixing the HTMLifier, but I'm not sure what's broken

**Comment by iPaCXgames** [comment]
I find whats broked...
Accually edge sensing is freak out comlitly. U cant detect if touching
edge... And go to mouse pointer is a bit off. Object that follows cursor
moves faster than mouse pointer. So i hope u fix it !!!

wt., 26 maj 2020, 21:27 użytkownik Sean <notifications@github.com> napisał:

**Comment by iPaCXgames** [comment]
And also on HTMLilifer page it says that u can see previous versions on
Github but I couldnt find them...


wt., 26 maj 2020 o 21:48 iPaCX Games <ipacx.yt@gmail.com> napisał(a):

**Comment by SheepTester** [comment]
You can access previous versions in the [commit history](https://github.com/SheepTester/htmlifier/commits/master) (though since the repository recently moved, most of the commit history so far is [in the old repository](https://github.com/SheepTester/words-go-here/commits/master/htmlifier))

I'll investigate what is wrong with the touching blocks

**Comment by SheepTester** [comment]
Here's a direct download for the offline HTMLifier for [the 2020-03-29 version](https://github.com/SheepTester/words-go-here/releases/tag/htmlifier-2020-03-29)

**Comment by wild-gamer** [comment]
> Here's a direct download for the offline HTMLifier for [the 2020-03-29 version](https://github.com/SheepTester/words-go-here/releases/tag/htmlifier-2020-03-29)

Could you put link to the may version?
