### ISSUE TITLE
Using Cloud Vars by HTMLified Project

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#78]
**Is it possible for two HTMLified projects on Github pages to use the same cloud variable?**
I want to use it such that, one project will set different values to a cloud variable, and the other project at a diff location will get those values and execute accordingly.

### Can u pls guide me?

**Comment by SheepTester** [comment]
If you're using localStorage, then if the cloud variables have the same name, they'll be shared. The two projects also have to be on the same domain.

If you're using a cloud server, you can use the same cloud server, as long as it doesn't distinguish between projects. The HTMLifier sends the ID in the project ID field (regardless of whether you're HTMLifying by file or from the Scratch website); if you're using my primitive cloud server, it does distinguish between project IDs, so make sure they're the same.

**Comment by SparkScratch-P** [comment]
**Thanks for it!** but is there a way I can create a server, maybe from Replit.com, that doesn't distinguish?

**Comment by SheepTester** [comment]
Yes; you need to create a websocket server; read [these details](https://github.com/SheepTester/primitive-cloud-server#details) about what it receives from and must send to the client

**Comment by SparkScratch-P** [comment]
thanks
