### ISSUE TITLE
Customize for Pictoblox

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#79]
I am very happy with ur HTMLifier for it is the **most professional packager** for sb3. Bt being a hardware dev, I would suggest making compatible with pictoblox, or at least help how to take in Arduino and other extensions and boards from it.
Pls Help

**Comment by SheepTester** [comment]
Is it open source?

**Comment by SparkScratch-P** [comment]
Sorry no

**Comment by SheepTester** [comment]
Then I can't make a converter for it, unfortunately

**Comment by SparkScratch-P** [comment]
Sorry for that, I understand, but I am in a problem... Is it possible to **create a scratch running environment online,** like it will run the scratch project only in full-screen mode! A webpage capable of running and **no editing**. This will be a great help. The main problem is much more. It will be created in a repo in GitHub, which users will fork and take to their own repos.... now what they will do is that, change a file names 'project.sb3' to one of their wish and then rename it as 'project.sb3', i.e **the file will be only capable of running an sb3 file named project.sb3 from its own repo. So, finally, when we launch it with Github pages, providing the URL**  username.github.io/reponame , it will open a scratch project as on the full page mode, and will not be possible to go to the editor.

### It would obv be very popular.

**Comment by SheepTester** [comment]
It would require a command line build step that would hinder its effectiveness, and I'm not sure if GitHub Actions, which I'm not familiar with, carries over to forks.



> it will run the scratch project only in full-screen mode!

Isn't this the repository you're commenting on?
