### ISSUE TITLE
I would like to use this in my nw.js file.

### ISSUE THREAD

**Issue by robloxboy24** [SheepTester/htmlifier#84]
I would like to use this (With credit) for one of my projects, can you tell me how to edit the file? (It's really long. [The offline version])

**Comment by SheepTester** [comment]
My [large file editor](https://sheeptester.github.io/words-go-here/htmlifier/large-file-editor/) hides the longer lines so that it's easier to edit the file

**Comment by robloxboy24** [comment]
Okay. Will give you the finished project soon. Thanks,   
- Robloxboy24
