### ISSUE TITLE
set server ip  to which server?

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/htmlifier#85]
Does the cloud var, `set server ip ` change the IP Address of the Host Server or the Cloud Variable storage server? 
 If it does to the Cloud Var Host server, is it like, whatever server we want, we can just switch to that set of cloud variables from the JS project, in any server? If yes, pls say that what to put in the cloud vars server section of HTMLifier, where we put `WS://` server id.

**Comment by SheepTester** [comment]
`set server ip` changes the cloud variable storage server. You can set it to any server that works. In the htmlifier, you should put the initial cloud server to use before `set server ip` is set

**Comment by SparkScratch-P** [comment]
**Thanks a Lot!**
