### ISSUE TITLE
Cloud Servers

### ISSUE THREAD

**Issue by JaredYoshi** [SheepTester/htmlifier#88]
Its possible use my website/hosting server as cloud server for htmlifer
or theres a way about how to use cloud variables without using localhost?
PD: for the hosting, i use freewha.com, also, forkphorus uses fosshost for the cloud variables, but htmlifer is better

**Comment by SheepTester** [comment]
Yes, if you use a hosting service for the cloud server, just put the domain or IP of that server

**Comment by JaredYoshi** [comment]
> Yes, if you use a hosting service for the cloud server, just put the domain or IP of that server

a domain, like "mygame.tk" ??
pd: thanks for the help, i really love htmlifier

**Comment by SheepTester** [comment]
> a domain, like "mygame.tk" ??

Yes, for whatever is hosting the cloud server. If the cloud server is listening to WebSocket connections on port 3000, then you can put `ws://mygame.tk:3000/`

**Comment by JaredYoshi** [comment]
What about github pages, i can use it?

**Comment by SheepTester** [comment]
No

**Comment by SheepTester** [comment]
I'm assuming this has been resolved
