### ISSUE TITLE
htmlifier doesn't show video

### ISSUE THREAD

**Issue by Can202** [SheepTester/htmlifier#93]
this project (not mine): https://scratch.mit.edu/projects/530465095/

if you convert to html, it don't show the video of the beginning
screenshot from video
![Screenshot_2021-05-17 Scratch - _-‾_-‾ Surfer _-‾_-‾ #games](https://user-images.githubusercontent.com/67566612/118513490-c1405080-b701-11eb-976f-e4b4737f4df2.png)

**Comment by SheepTester** [comment]
The intro animation shows for me, but the sound doesn't play automatically because of the autoplay policy, which prevents websites from automatically playing sounds; is that what you're referring to?

**Comment by Can202** [comment]
The intro animation doesn't show for me, temporarily I upload this game to: https://can202.github.io/Surfer.html
I'm on Firefox, but just in case i tried it in microsoft edge
it doesn't work

**Comment by Can202** [comment]
Video


https://user-images.githubusercontent.com/67566612/118544009-0a54cc80-b723-11eb-96a6-e5d1d14f7b3e.mp4

**Comment by SheepTester** [comment]
What did you set the username value to? The project skips the intro if the username is one of the developers:

![image](https://user-images.githubusercontent.com/22133785/118544178-1e400480-b70a-11eb-8da1-533795a63c31.png)

**Comment by Can202** [comment]
ahhh
i put the creator name
crystal-25

**Comment by Can202** [comment]
that's all

sorry for the problems

Thanks

**Comment by Can202** [comment]
now The intro animation works
