### ISSUE TITLE
"pasted" variable (use google translator)

### ISSUE THREAD

**Issue by WormPatch** [SheepTester/htmlifier#95]
hola, les quiero decir que yo estoy en un proyecto de un juego ritmico.
en una parte del juego esta la opcion de copiar el nivel y pegar el nivel, todo iba bien, el juego podia copiar el nivel facil mente, pero cuando use la variable "pasted" no funcionaba.

**Comment by SheepTester** [comment]
Es necesario presionar ctrl + V para cambiar el valor de la variable `☁ pasted` porque páginas web no pueden leer del portapapeles directamente por razones de seguridad. También creo que unos navegadores web solo permiten el aceso al portapapeles del usador cuando el usador pega en un campo de texto. Pues, recomiendo que uses el bloque `preguntar _ y esperar` porque usa un campo de texto típico y pues es más fidedigno

**Comment by SheepTester** [comment]
Creo que ya he añadido este en 92fb62f53f380f457187790eef8eb1ac6ad67a14
