### ISSUE TITLE
When you reload, some yellow appears.

### ISSUE THREAD

**Issue by era2010-coder** [SheepTester/htmlifier#96]
When you reload, some yellow appears on the project id/file/url spot.

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/119582586-a1500300-bd79-11eb-9e4e-fd8f2f3ecf54.png)
That's probably the log. The options are generated by JavaScript so they appear a short moment after the page loads.

I don't think this is a bug, so I'll close this
